services:
  - type: web
    name: car-rental-system
    env: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: cd Backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0